// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/spire-onboarding/BridgeConsole.tsx": () => import("../components/mockups/spire-onboarding/BridgeConsole.tsx"),
  "./components/mockups/spire-onboarding/FieldNotebook.tsx": () => import("../components/mockups/spire-onboarding/FieldNotebook.tsx"),
  "./components/mockups/spire-onboarding/MarineDoctrine.tsx": () => import("../components/mockups/spire-onboarding/MarineDoctrine.tsx")
};
